# Generated by Django 5.0.4 on 2024-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANO', models.PositiveBigIntegerField(max_length=20, unique=True)),
                ('ANAME', models.CharField(max_length=20)),
            ],
        ),
    ]
