# Generated by Django 5.0.4 on 2024-04-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HcyAccount',
            fields=[
                ('ano', models.DecimalField(db_comment='account number', decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('aname', models.CharField(db_comment='account name', max_length=20)),
                ('adoopen', models.DateTimeField(db_comment='date opened')),
                ('a_type', models.CharField(db_comment='account type', max_length=1)),
                ('baptno', models.CharField(blank=True, db_comment='Bank apartment number', max_length=10, null=True)),
            ],
            options={
                'db_table': 'hcy_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyCity',
            fields=[
                ('cid', models.IntegerField(db_comment='CITY ID', primary_key=True, serialize=False)),
                ('cname', models.CharField(db_comment='CITY NAME', max_length=20)),
            ],
            options={
                'db_table': 'hcy_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyCustomer',
            fields=[
                ('cusfname', models.CharField(db_comment='customer first name', max_length=20)),
                ('cuslname', models.CharField(db_comment='customer last name', max_length=20)),
                ('cemail', models.CharField(db_comment='customer email', max_length=20, primary_key=True, serialize=False)),
                ('captno', models.CharField(blank=True, db_comment='customer apartment numbner', max_length=10, null=True)),
            ],
            options={
                'db_table': 'hcy_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyState',
            fields=[
                ('sid', models.IntegerField(db_comment='STATE ID', primary_key=True, serialize=False)),
                ('sname', models.CharField(db_comment='STATE NAME', max_length=20)),
            ],
            options={
                'db_table': 'hcy_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyStreet',
            fields=[
                ('stid', models.IntegerField(db_comment='STREET ID', primary_key=True, serialize=False)),
                ('stname', models.CharField(db_comment='STREET NAME', max_length=20)),
            ],
            options={
                'db_table': 'hcy_street',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyUniversity',
            fields=[
                ('uniid', models.SmallIntegerField(db_comment='University ID', primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, db_comment='University Name', max_length=30, null=True)),
            ],
            options={
                'db_table': 'hcy_university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyZip',
            fields=[
                ('zipcode', models.DecimalField(db_comment='Zipcode', decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hcy_zip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyChecking',
            fields=[
                ('ano', models.OneToOneField(db_column='ano', db_comment='account number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.hcyaccount')),
                ('csercharge', models.DecimalField(db_comment='MONTHLY ACCOUNT MAINTENANCE FEES', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'hcy_checking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyLoan',
            fields=[
                ('ano', models.OneToOneField(db_column='ano', db_comment='account number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.hcyaccount')),
                ('lrate', models.DecimalField(db_comment='loan rate', decimal_places=2, max_digits=10)),
                ('lamount', models.DecimalField(db_comment='LOAN AMOUNT', decimal_places=2, max_digits=10)),
                ('lmonths', models.IntegerField(db_comment='LOAN MONTHS')),
                ('lpayments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l_type', models.CharField(db_comment='LOAN TYPE', max_length=1)),
            ],
            options={
                'db_table': 'hcy_loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcySavings',
            fields=[
                ('ano', models.OneToOneField(db_column='ano', db_comment='account number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.hcyaccount')),
                ('sintrate', models.DecimalField(db_comment='SAVINGS INTEREST RATE', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'hcy_savings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyHome',
            fields=[
                ('ano', models.OneToOneField(db_column='ano', db_comment='account number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.hcyloan')),
                ('hbuily', models.DateTimeField(db_comment='home built year')),
                ('hinsacc', models.FloatField(db_comment='home insurance account number', unique=True)),
                ('hinsname', models.CharField(db_comment='home insurance name', max_length=20)),
                ('hinyearly', models.DecimalField(db_comment='home insurance yearly insurance premium', decimal_places=2, max_digits=10)),
                ('haptno', models.CharField(blank=True, db_comment='House apartment number', max_length=10, null=True)),
            ],
            options={
                'db_table': 'hcy_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcyStudent',
            fields=[
                ('ano', models.OneToOneField(db_column='ano', db_comment='account number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='projects.hcyloan')),
                ('stuid', models.CharField(db_comment='student id', max_length=20, unique=True)),
                ('sgrad', models.FloatField(db_comment='student is grad or undergrad')),
                ('sexpgraddate', models.DateTimeField(db_comment='exptected graduation')),
            ],
            options={
                'db_table': 'hcy_student',
                'managed': False,
            },
        ),
    ]
