# Generated by Django 5.0.4 on 2024-04-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSFNAME', models.CharField(max_length=20)),
                ('CUSLNAME', models.CharField(max_length=20)),
            ],
        ),
    ]
